# Generated by Django 5.0.7 on 2024-08-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedloginattempt',
            name='password_change_required',
            field=models.BooleanField(default=False),
        ),
    ]
